name: lexmory
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  flutter_native_splash: ^2.4.4
  google_mobile_ads: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/app_icon.png"
  adaptive_icon_background: "#0F0F10"
  adaptive_icon_foreground: "lib/assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/splash/splash.png
    - lib/assets/icon/lexmory_native_splash.png
    - lib/assets/icon/native_splash.png
    - lib/assets/images/splash/app_splash.png
    - lib/assets/library/room_01/

flutter_native_splash:
  color: "#0F0F10"
  image: lib/assets/icon/native_splash.png

  android_12:
    color: "#0F0F10"
    image: lib/assets/icon/native_splash.png
    icon_background_color: "#0F0F10"

  android: true
  ios: true
  web: false
