name: lexmory
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4

# Uygulama ikon ayarları kalıyor
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/lexmory_icon.png"
  adaptive_icon_background: "#1A1A1A"
  adaptive_icon_foreground: "lib/assets/icon/lexmory_icon.png"

flutter:
  uses-material-design: true

  # Kendi Splash Screen'in için gerekli görsel asset'i
  assets:
    - lib/assets/images/splash/splash.png

flutter_native_splash:
  color: "#1A1A1A"
  image: lib/assets/icon/lexmory_icon.png

  android_12:
    color: "#1A1A1A"
    image: lib/assets/icon/lexmory_icon.png
    icon_background_color: "#1A1A1A"

